// packages/vue/src/adCAPTCHA.vue
<template>
    <div :data-adcaptcha="placementID"></div>
  </template>
  
  <script lang="ts">
  import { ref, onMounted, watch } from 'vue';
  import { loadScript } from './util';
  
  export default {
    name: 'AdCaptcha',
    props: {
      placementID: {
        type: String,
        required: true,
      },
      onComplete: {
        type: Function,
        default: undefined,
      },
    },
    setup(props) {
      const onCompleteRef = ref<(() => void) | undefined>(props.onComplete);
  
      watch(() => props.onComplete, (newOnComplete) => {
        onCompleteRef.value = newOnComplete;
      });
  
      onMounted(() => {
        loadScript().then(() => {
          if (onCompleteRef.value) {
            window.adcap.setupTriggers({
              onComplete: onCompleteRef.value,
            });
          }
        }).catch((err) => {
          console.error('Error loading adCAPTCHA script:', err);
        });
      });
  
      return {
        placementID: props.placementID,
      };
    },
  };
  
  export const setKeywords = (keywords: string[]) => {
    if (window.adcap) {
      window.adcap.setKeywords(keywords);
    }
  };
  
  export const getSuccessToken = () => window.adcap ? window.adcap.successToken : null;
  </script>

// packages/angular/projects/adcaptcha/src/lib/adcaptcha.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { AdcaptchaService } from './adcaptcha.service';

@Component({
  selector: 'lib-adcaptcha',
  template: `<div [attr.data-adcaptcha]="placementID"></div>`
})
export class AdcaptchaComponent implements OnInit {

  @Input() placementID: string = '';
  @Input() onComplete?: () => void;

  constructor(private adcaptchaService: AdcaptchaService) {}

  ngOnInit(): void {
    this.setupAdCAPTCHA();
  }

  private setupAdCAPTCHA() {
    this.adcaptchaService.loadScript().then(() => {
      if (this.onComplete) {
        window.adcap.setupTriggers({
          onComplete: this.onComplete,
        });
      }
    }).catch(error => {
      console.error('Error loading the script:', error);
    });
  }

  setKeywords(keywords: string[]): void {
    this.adcaptchaService.setKeywords(keywords);
  }

  getSuccessToken(): string {
    return this.adcaptchaService.getSuccessToken();
  }
}
