// examples/vue/src/components/Footer.vue
<template>
    <footer class="footer">
      <div class="footer-content">
        <p class="copyright">© 2024 adCAPTCHA. All rights reserved.</p>
      </div>
    </footer>
  </template>

  <style scoped>
  .footer {
    background-color: #222; 
    color: #fff; 
    padding: 2rem 0;
    text-align: center;
  }
  
  .footer-content {
    max-width: 1200px;
    margin: 0 auto; 
    padding: 0 1rem;
  }
  
  .copyright {
    font-size: 1rem;
    margin-bottom: 1rem;
  }
  </style>

// examples/svelte/src/components/Footer.svelte
<footer class="footer">
  <div class="footer-content">
    <p class="copyright">© 2024 adCAPTCHA. All rights reserved.</p>
  </div>
</footer>

<style>
  .footer {
    background-color: #222; 
    color: #fff; 
    padding: 2rem 0;
    text-align: center;
  }

  .footer-content {
    max-width: 1200px;
    margin: 0 auto; 
    padding: 0 1rem;
  }

  .copyright {
    font-size: 1rem;
    margin-bottom: 1rem;
  }
</style>
