// packages/react/src/adCAPTCHA.tsx
import React from 'react';
import { loadScript } from './util';

interface AdCAPTCHAProps {
  placementID: string;
  onComplete?: () => void;
}
const AdCAPTCHA = (props: AdCAPTCHAProps) => {
  loadScript().then(() => {
    if (!props.onComplete) return;

    window.adcap.setupTriggers({
      onComplete: props.onComplete,
    });
  });

  return (
    <div data-adcaptcha={props.placementID} />
  );
}

export const getSuccessToken = () => window.adcap.successToken;

export default AdCAPTCHA;

// packages/svelte/src/lib/adCAPTCHA.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { loadScript } from './util.ts';

    type OnCompleteHandler = () => void;
  
    export let placementID: string;
    export let onComplete: OnCompleteHandler | undefined;

    onMount(() => {
      async function setupTriggers() {
        await loadScript();
        
        if (window.adcap && onComplete) {
          window.adcap.setupTriggers({ onComplete });
        }
      }
  
      setupTriggers();
    });
  </script>
  
  <div data-adcaptcha={placementID}></div>
