// examples/vue/src/App.vue
<script setup lang="ts">
import Navbar from './components/Navbar.vue';
import HeroSection from './components/HeroSection.vue';
import ContactForm from './components/ContactForm.vue';
import Footer from './components/Footer.vue';
</script>

<template>
  <div id="app">
    <Navbar />
    <HeroSection />
    <ContactForm />
    <Footer />
  </div>
</template>

// examples/svelte/src/App.svelte
<script>
  import Navbar from './components/Navbar.svelte';
  import Banner from './components/Banner.svelte';
  import ContactForm from './components/ContactForm.svelte';
  import Footer from './components/Footer.svelte';
</script>

<main>
  <Navbar />
  <Banner />
  <ContactForm />
  <Footer />
</main>
